import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Copy, Check, Download, MessageSquare, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface DraftSummaryProps {
  summary: string;
}

function generatePDF(summary: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 25;

  // Header bar
  doc.setFillColor(37, 99, 235); // primary blue
  doc.rect(0, 0, pageWidth, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("PULSE AI — EXECUTIVE SUMMARY", margin, 8);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin, 8, { align: "right" });

  // Title
  y = 25;
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Feedback Summary Report", margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Body text
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);

  const lines = doc.splitTextToSize(summary, maxWidth);
  for (const line of lines) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  // Footer
  y += 10;
  doc.setDrawColor(229, 231, 235);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by Pulse AI · Sentiment & Synthesis Dashboard", margin, y);

  doc.save("pulse-ai-summary.pdf");
}

export function DraftSummary({ summary }: DraftSummaryProps) {
  const [isGenerated, setIsGenerated] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const handleGenerate = () => {
    setIsGenerated(true);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePDFExport = () => {
    setIsExporting(true);
    try {
      generatePDF(summary);
      toast.success("PDF downloaded successfully");
    } catch {
      toast.error("Failed to generate PDF");
    } finally {
      setIsExporting(false);
    }
  };

  const handleSlackPost = () => {
    toast.info("Slack not connected yet. Connect Slack in project settings to enable posting.");
  };

  return (
    <div className="space-y-3">
      {!isGenerated ? (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex flex-col items-center justify-center py-8 text-center"
        >
          <div className="h-12 w-12 rounded-xl bg-accent flex items-center justify-center mb-3">
            <FileText size={20} className="text-accent-foreground" />
          </div>
          <p className="text-sm text-muted-foreground mb-4 max-w-[200px]">
            Generate an executive summary from all analyzed feedback
          </p>
          <Button onClick={handleGenerate} size="sm">
            Draft Report
          </Button>
        </motion.div>
      ) : (
        <AnimatePresence>
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="space-y-3"
          >
            <div className="rounded-lg bg-surface-sunken p-4 text-sm leading-relaxed text-card-foreground whitespace-pre-line">
              {summary}
            </div>

            {/* Export buttons */}
            <div className="grid grid-cols-3 gap-2">
              <Button
                variant="outline"
                size="sm"
                className="text-xs gap-1.5"
                onClick={handleCopy}
              >
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="text-xs gap-1.5"
                onClick={handlePDFExport}
                disabled={isExporting}
              >
                {isExporting ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
                PDF
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="text-xs gap-1.5"
                onClick={handleSlackPost}
              >
                <MessageSquare size={13} />
                Slack
              </Button>
            </div>

            <p className="text-[10px] text-muted-foreground text-center">
              Export as PDF or post to Slack
            </p>
          </motion.div>
        </AnimatePresence>
      )}
    </div>
  );
}
